---
- name: Installing Apache2 in salve-node through variables
  hosts: all
  become: yes
  vars_files:
  - vars.yaml


  tasks:
    - name: Installing apache2 in slave-node by using variables
      apt:
        name: "{{apache2_server}}"
        state: latest
        update_cache: yes

    - name: Apache2 start on slave-node
      service:
        name: "{{apache2_server}}"
        state: started

    - name: Apache2 restart on slave-node
      service:
        name: "{{apache2_server}}"
        state: restarted
